baseurl = "https://nineteneleven.org"
languageCode = "en-gb"
theme = "hugo-theme-shell"
paginate = 5

[Params]
  description = "Faith-Driven Code, Crafting Apps with Purpose"
  [Params.Terminal]
    scheme = "Dracula"
    userName = "web"
    pcName = "nineteneleven.org"
    workDir = "about"
    profile = "profile.txt"

    ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
    stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
    commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

    titleDelay = 0 # title speed : "title" in front matter
    contentDelay = 0 # content speed : content in .md file

    description = "/description.md"

  [Params.Tree]
    use = true
    folderName = "apps"
    files = [["DailyVerse", "https://dailyverse.uk/"]]
